#!/bin/bash
#Kazi Wahedullah
#Part 1b. Note Location

help (){
echo "You can search for notes using these options:"

  echo "Option 1: ./<script name> -d yyyy-mm-dd or just mm-dd to display all files created on that date"
  echo "Option 2: ./<script name> -t tag1  this will search through all of the notes in the notes directory for the tags"
  echo "Option 3: ./<script name> -n notename to display a the with the name provided no need to specify .txt"
}



NOTES_FOLDER=($HOME/notes)



while getopts ":d:t:n:" options; do
  case ${options} in
    d)
      DATE=${OPTARG}
      grep -rl "Date:" $NOTES_FOLDER | xargs grep -rl $DATE #rl is recursive and file with matches, xargs can be thought of as turning its stdin into arguments to the given commands , above greps the Date field in all files in NOTES_FOLDER  sends it as an argument to xargs where we grep again for the date specified to find matches
      # printf ${x}
      read -p "Please enter just the name of the note you would like to read including .txt:" FILE_SELECTED
      echo -e "\nThese are the contents of the file:\n"
      cat ${NOTES_FOLDER}"/"${FILE_SELECTED}
      echo -e "\n"
      
      ;;
    t)
      TAG=${OPTARG}
      grep -rl "Tags:" $NOTES_FOLDER | xargs grep -rl "#$TAG"
      read -p "Please enter just the name of the note you would like to read including .txt: " FILE
      echo -e "\n"
      cat ${NOTES_FOLDER}"/"${FILE}

      ;;
    n)
      TITLE=${OPTARG}
      echo -e "\nThese are the contents of the file:\n"
      cat "${NOTES_FOLDER}/${TITLE}.txt"
      echo -e "\n"
      ;;
    *|h)
      help
      exit 0
      ;;
  esac
done