#!/bin/bash
#Kazi Wahedullah
#Part 1a. Note Creation

help (){
echo "This program will prompt you to create a note, it should have a title, tags are optional. The notes will be stored in "'$HOME/notes'
}

help


NOTES_FOLDER=($HOME/notes)

if [ ! -d  "${NOTES_FOLDER}" ]; then
  mkdir ${NOTES_FOLDER}
fi 


read -p "Enter a title: " TITLE


while [ -f ${NOTES_FOLDER}/${TITLE} ]; do
  read -p "$TITLE exists already, please enter a different title: " TITLE 
done #use -p otherwise display issue 

echo "Date:"`date +%Y-%m-%d` >> "${NOTES_FOLDER}/${TITLE}.txt" #Using backticks otherwise date will not get posted 
echo "Please type your note and press enter, then ctrl+d when you are done entering your note"


while IFS= read line; do # Could use read -r
  printf "${line}\n" >> "${NOTES_FOLDER}/${TITLE}.txt" #not using echo due to \n
done

read -p "Enter Any tags you would like to add:  " TAGS
echo "Tags: #$TAGS" >> "${NOTES_FOLDER}/${TITLE}.txt"


