#!/bin/bash
#Kazi Wahedullah
#Part 2 Sys Info



clear
printf "HELP: run script as project_2 or as project_2 -t to see tux\n"
printf "i.e. project_2 -t\n"

# sleep 1


UPTIME=$(uptime | awk '{ print $5 }'| sed 's/,//g')

DISTRO=$(cat /etc/*-release | egrep "PRETTY_NAME" | cut -d = -f 2 | tr -d '"' | tac | tr '\n' ' ')
SHELL=$SHELL
PACKAGES=$(apt list --installed | wc -l ) 2> /dev/null
MEMORY_AVAILABLE=$(awk '/MemFree/ { printf "%.2f \n", $2/1024/1024 }' /proc/meminfo)
MEM_CACHE=$(grep "Cached" /proc/meminfo | awk 'NR==1 { printf "%.2f \n", $2/1024/1024 }')
MEM_TOTAL=$(grep "MemTotal" /proc/meminfo | awk 'NR==1 { printf "%.2f \n", $2/1024/1024 }')

MEMORY_USED=$(bc -l <<<"${MEM_TOTAL}-${MEM_CACHE}-${MEMORY_AVAILABLE}")
# CAN ALSO USE result=$(awk '{print $1*$2}' <<<"${NUM} ${MEGA}")

SELECTION=''
while getopts :t arg; do
  case ${arg} in
    t)
      SELECTION='t'
      ;;
    *|h)
        SELECTION=''
      ;;
    esac
done

stats(){
RED='\033[0;31m'
NC='\033[0m'

printf "${RED}hostname:       %15s$(hostname) \n"
printf "user:           %15s$USER \n"
printf "uptime:         %15s$UPTIME \n"
printf "distro:         %15s$DISTRO \n"
printf "kernel:         %15s$(uname -r) \n"
printf "shell:          %15s${SHELL:5} \n"   # item 5 onwards slicing 
printf "packages:       %15s${PACKAGES} \n"   
printf "mem available:  %15s${MEMORY_AVAILABLE}Gi \n"   
printf "mem used:      %15s  ${MEMORY_USED} Gi \n\n${NC}"   
 
}

tux(){
PURPLE='\033[1;35m'
NC='\033[0m'
printf "${PURPLE}" 
printf "               .--.     \n"
printf "              |o_o |    \n"
printf "              |:_/ |    \n"
printf "             //   \ \   \n"
printf "            (|     | )  \n"
printf "           /'\_   _/\`\ \n"
printf "           \___)=(___/  \n${NC}"

}

if [ "${SELECTION}" = '' ]; then
  stats
fi


if [ "${SELECTION}" = 't' ]; then
  tux
  stats
fi


